---
- name: Déployer l'infrastructure sur Cloud
  remote_user: ubuntu
  hosts: all
  become: true

  tasks:
    - name: Copier le script d'installation sur la machine
      copy:
        src: ./script.sh
        dest: /home/ubuntu/script.sh
        mode: '0755'

    - name: Exécuter le script
      command: bash /home/ubuntu/script.sh

    - name: Définir le nouveau hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Modifier /etc/hosts
      replace:
        path: /etc/hosts
        regexp: '^(127\.0\.1\.1\s+).*'
        replace: '\1{{ inventory_hostname }}'